// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: internal/transport/grpc/proto/replication.proto

package replication

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PushStateRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Identifies the CRDT instance on the receiving node
	CrdtId int64 `protobuf:"varint,1,opt,name=crdt_id,json=crdtId,proto3" json:"crdt_id,omitempty"`
	// CRDT type ("gcounter", "gset", "lwwset", ...)
	CrdtType string `protobuf:"bytes,2,opt,name=crdt_type,json=crdtType,proto3" json:"crdt_type,omitempty"`
	// Serialized CRDT state
	State         []byte `protobuf:"bytes,3,opt,name=state,proto3" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushStateRequest) Reset() {
	*x = PushStateRequest{}
	mi := &file_internal_transport_grpc_proto_replication_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushStateRequest) ProtoMessage() {}

func (x *PushStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_transport_grpc_proto_replication_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushStateRequest.ProtoReflect.Descriptor instead.
func (*PushStateRequest) Descriptor() ([]byte, []int) {
	return file_internal_transport_grpc_proto_replication_proto_rawDescGZIP(), []int{0}
}

func (x *PushStateRequest) GetCrdtId() int64 {
	if x != nil {
		return x.CrdtId
	}
	return 0
}

func (x *PushStateRequest) GetCrdtType() string {
	if x != nil {
		return x.CrdtType
	}
	return ""
}

func (x *PushStateRequest) GetState() []byte {
	if x != nil {
		return x.State
	}
	return nil
}

var File_internal_transport_grpc_proto_replication_proto protoreflect.FileDescriptor

const file_internal_transport_grpc_proto_replication_proto_rawDesc = "" +
	"\n" +
	"/internal/transport/grpc/proto/replication.proto\x12\vreplication\x1a\x1bgoogle/protobuf/empty.proto\"^\n" +
	"\x10PushStateRequest\x12\x17\n" +
	"\acrdt_id\x18\x01 \x01(\x03R\x06crdtId\x12\x1b\n" +
	"\tcrdt_type\x18\x02 \x01(\tR\bcrdtType\x12\x14\n" +
	"\x05state\x18\x03 \x01(\fR\x05state2X\n" +
	"\x12ReplicationService\x12B\n" +
	"\tPushState\x12\x1d.replication.PushStateRequest\x1a\x16.google.protobuf.EmptyB\x0eZ\f/replicationb\x06proto3"

var (
	file_internal_transport_grpc_proto_replication_proto_rawDescOnce sync.Once
	file_internal_transport_grpc_proto_replication_proto_rawDescData []byte
)

func file_internal_transport_grpc_proto_replication_proto_rawDescGZIP() []byte {
	file_internal_transport_grpc_proto_replication_proto_rawDescOnce.Do(func() {
		file_internal_transport_grpc_proto_replication_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_transport_grpc_proto_replication_proto_rawDesc), len(file_internal_transport_grpc_proto_replication_proto_rawDesc)))
	})
	return file_internal_transport_grpc_proto_replication_proto_rawDescData
}

var file_internal_transport_grpc_proto_replication_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_internal_transport_grpc_proto_replication_proto_goTypes = []any{
	(*PushStateRequest)(nil), // 0: replication.PushStateRequest
	(*emptypb.Empty)(nil),    // 1: google.protobuf.Empty
}
var file_internal_transport_grpc_proto_replication_proto_depIdxs = []int32{
	0, // 0: replication.ReplicationService.PushState:input_type -> replication.PushStateRequest
	1, // 1: replication.ReplicationService.PushState:output_type -> google.protobuf.Empty
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_transport_grpc_proto_replication_proto_init() }
func file_internal_transport_grpc_proto_replication_proto_init() {
	if File_internal_transport_grpc_proto_replication_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_transport_grpc_proto_replication_proto_rawDesc), len(file_internal_transport_grpc_proto_replication_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_transport_grpc_proto_replication_proto_goTypes,
		DependencyIndexes: file_internal_transport_grpc_proto_replication_proto_depIdxs,
		MessageInfos:      file_internal_transport_grpc_proto_replication_proto_msgTypes,
	}.Build()
	File_internal_transport_grpc_proto_replication_proto = out.File
	file_internal_transport_grpc_proto_replication_proto_goTypes = nil
	file_internal_transport_grpc_proto_replication_proto_depIdxs = nil
}
