mode: live

node_defaults:
  crdt: gcounter
  host: localhost

nodes:
  A:
    http_port: 8001
    grpc_port: 9001

  B:
    http_port: 8002
    grpc_port: 9002

  C:
    http_port: 8003
    grpc_port: 9003

  D:
    http_port: 8004
    grpc_port: 9004

  E:
    http_port: 8005
    grpc_port: 9005
